export const API_ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  MISSING_PARAMETER: "MISSING_PARAMETER",
  INVALID_PARAMETER_FORMAT: "INVALID_PARAMETER_FORMAT",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_USERNAME_ALREADY_EXISTS: "USER_USERNAME_ALREADY_EXISTS",

  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  MAIL_SERVICE_UNAVAILABLE: "MAIL_SERVICE_UNAVAILABLE",
  ACTIVATION_LINK_ALREADY_EXISTS: "ACTIVATION_LINK_ALREADY_EXISTS",
  ACTIVATION_LINK_EXPIRED: "ACTIVATION_LINK_EXPIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  REQUIRED: "REQUIRED",
  TOO_SHORT: "TOO_SHORT",
  INVALID_EMAIL: "INVALID_EMAIL",
  AT_LEAST_ONE_FIELD_REQUIRED: "AT_LEAST_ONE_FIELD_REQUIRED",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
